Выполнена верстка button
BVyacheslav/admin-panel-makeup pull request #7
Opened 2022-02-23 06:37 UTC by BVyacheslav

https://bvyacheslav.github.io/admin-panel-makeup/

2022-03-04 07:33 UTC, Muslik requested changes
Есть замечания

2022-03-04 07:33 UTC, Muslik commented on blocks/ui-kit.html
> +        <button class="button button_white">Text here</button>
То что также как вы для каждой тесы создали свой модификатор, тоже самое нужно сделать и для размеров. То есть у большой кнопки должен быть класс аля button_size_medium и у нее указываете размеры

2022-03-04 07:33 UTC, Muslik commented on blocks/ui-kit.html
> +            class="button__icon button__icon_before-text"
button__icon_before-text класса быть не должно. button__icon вообще можно сделать просто .icon.
Что мы получаем в итоге: .icon полностью независима. Она не знает где мы ее используем. Отступ от текста до иконки вы делаете при помощи классов button. (Текст внутри кнопки всегда оборачиваете в span, задаете класс, и выставляете margin для текста в зависимости от наличия внутри button класса .icon

2022-03-04 07:33 UTC, Muslik commented on blocks/button.css
> +  background: none;
background: none можно задать самой кнопке. А далее уже выставлять background где он нужен

2022-03-04 07:33 UTC, Muslik commented on blocks/button.css
> +  margin-bottom: 16px;
Не может быть никаких отступов у блока button. Он не знает где я его могу использовать. Отступ должен задавать его родитель через элемент.

2022-03-04 07:33 UTC, Muslik commented on blocks/button.css
> +  padding: 48px 48px;
просто 48px

2022-03-10 03:02 UTC, BVyacheslav commented on blocks/button.css
> +  padding: 48px 48px;
Исправил замечания, прошу проверить

2022-03-13 17:27 UTC, Muslik requested changes
https://ibb.co/vBMkXxx

2022-03-14 01:50 UTC, BVyacheslav commented
Исправил файл index.html для корректного отображения, прошу проверить

2022-03-22 15:59 UTC, Muslik approved these changes

2022-03-22 15:59 UTC, Muslik commented on blocks/ui-kit.html
> +        <button class="button button_white button_only-icon-small">
nit: У вас два разных модификатора для просто иконки внутри кнопки. У кнопки есть размер - medium, small. Так вот для того чтобы определить каким должен быть padding вы используете размер.
```html
<button class="button button_white button_small button_only-icon">
```

```css
.button_small.button_only-icon {}
```

И не нужно будет несколько модификаторов для размеров кнопки только с иконкой

2022-03-24 02:19 UTC, merged