Выполнена верстка dropdown
BVyacheslav/admin-panel-makeup pull request #8
Opened 2022-02-24 03:51 UTC by BVyacheslav

https://bvyacheslav.github.io/admin-panel-makeup/

2022-03-04 07:37 UTC, Muslik requested changes
В основном тут замечания из кнопки перетекли

2022-03-04 07:37 UTC, Muslik commented on blocks/ui-kit.html
> +          <div class="checkbox">
В figma этот блок тянется на всю ширину. У вас между строками есть отступ: https://ibb.co/wJC4bxL. Соответственно я могу кликнуть в пустое место между блоками и ничего не произойдет. Используйте padding

2022-03-04 07:37 UTC, Muslik commented on blocks/ui-kit.html
> +          <div class="checkbox">
С radio тоже самое

2022-03-04 07:37 UTC, Muslik commented on blocks/button.css
> +  margin-bottom: 0;
Угу ) Если вы исправите свой margin в блоке с кнопкой то тут его не придется обнулять

2022-03-10 03:02 UTC, BVyacheslav commented on blocks/button.css
> +  margin-bottom: 0;
Исправил замечания, прошу проверить

2022-03-13 17:28 UTC, Muslik requested changes
https://ibb.co/9Y4V75z

2022-03-14 01:50 UTC, BVyacheslav commented
Исправил файл index.html для корректного отображения, прошу проверить

2022-03-22 16:05 UTC, Muslik commented
https://ibb.co/Qcb1m28 - у вас между блоками пустое место. И если я в него кликаю то ничего не происходит. Блок должен занимать всю ширину - https://codepen.io/Dzhab/pen/BameMYx (Нет пустых мест, могу кликнуть куда угодно и чекбокс выберется)

2022-03-22 22:48 UTC, Muslik approved these changes
item-ы в dropdown-е должны центрироваться. То есть padding и сверху и снизу должен быть одинаковым. Они должный быть в центре.

2022-03-24 02:20 UTC, merged